from datetime import date

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI(title="Assignment API")


# This model describes the information a user sends to the API.
class AssignmentCreate(BaseModel):
    title: str = Field(min_length=3, max_length=100)
    due_date: date
    done: bool = False


# This model adds the ID generated by the API.
class Assignment(AssignmentCreate):
    id: int


# Assignments are stored here while the application is running.
assignments: list[Assignment] = []

# The first assignment will receive ID 1.
next_id = 1


@app.get("/")
def home():
    return {"message": "Welcome to the Assignment API"}


@app.post("/assignments", response_model=Assignment, status_code=201)
def create_assignment(assignment: AssignmentCreate):
    global next_id

    new_assignment = Assignment(
        id=next_id,
        title=assignment.title,
        due_date=assignment.due_date,
        done=assignment.done,
    )

    assignments.append(new_assignment)
    next_id = next_id + 1

    return new_assignment


@app.get("/assignments", response_model=list[Assignment])
def get_all_assignments():
    return assignments


@app.get("/assignments/{assignment_id}", response_model=Assignment)
def get_one_assignment(assignment_id: int):
    for assignment in assignments:
        if assignment.id == assignment_id:
            return assignment

    raise HTTPException(status_code=404, detail="Assignment not found")


@app.delete("/assignments/{assignment_id}")
def delete_assignment(assignment_id: int):
    for assignment in assignments:
        if assignment.id == assignment_id:
            assignments.remove(assignment)
            return {"message": "Assignment deleted successfully"}

    raise HTTPException(status_code=404, detail="Assignment not found")